spring:
    application:
        name: passport

server:
    session:
        timeout: 300
        cookie.httpOnly: true
        trackingModes: COOKIE #TODO check other options as well

cas:
    authn:
        policy:
            all:
                enabled: true

info:
  description: Passport Configuration
